export const FETCH_LOGIN = 'FETCH_LOGIN';
//DASHBOARD
export const INIT_DASHBOARD = 'INIT_DASHBOARD';
export const FETCH_SHOPS = 'FETCH_SHOPS';
export const RECEIVE_SHOPS = 'RECEIVE_SHOPS';
export const ERROR_RECEIVE_SHOPS = 'ERROR_RECEIVE_SHOPS';
export const OPEN_SHOP_FORM = 'OPEN_SHOP_FORM';
export const CLOSE_SHOP_FORM = 'CLOSE_SHOP_FORM';
export const FETCH_CREATE_SHOP = 'FETCH_CREATE_SHOP';
export const SUCCESS_CREATE_SHOP = 'SUCCESS_CREATE_SHOP';
export const ERROR_CREATE_SHOP = 'ERROR_CREATE_SHOP';
export const RESET_CREATE_SHOP = 'RESET_CREATE_SHOP';